FROM python:3.12.4-bullseye

WORKDIR /app

RUN git config --global --add safe.directory /app

# this pip install takes forever, look into how we can only do this on rebuild
RUN pip install ChatTTS faster-whisper

RUN apt-get update
RUN apt-get -y install ffmpeg
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /bin/yt-dlp
RUN chmod a+rx /bin/yt-dlp  # Make executable