version: '3'
services:
  content-generator:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ~/.gitconfig/:/etc/gitconfig
      - .:/app
    stdin_open: true
    tty: true
    command: bash
